/**
 * Builds the static assets into `public/` (served by Workers Static Assets):
 *
 * - content-hashed CSS, JS and logo under `/assets/` (cached immutable)
 * - the service worker at `/sw.js` (must stay unhashed for its scope)
 * - `_headers` with the caching rules
 * - `src/generated/assets.ts` with the hashed URLs for the HTML templates
 *
 * No dependencies: the CSS is only stripped of comments and whitespace, the
 * scripts are shipped as written (they are small and served compressed).
 */
import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const client = join(root, 'client');
const out = join(root, 'public');

function hash(content: string | Buffer) {
  return createHash('sha256').update(content).digest('hex').slice(0, 10);
}

function minifyCss(css: string) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .replace(/\s*([{};,>])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim();
}

async function emit(name: string, ext: string, content: string) {
  const file = `${name}.${hash(content)}.${ext}`;
  await writeFile(join(out, 'assets', file), content);
  return `/assets/${file}`;
}

await rm(out, { recursive: true, force: true });
await mkdir(join(out, 'assets'), { recursive: true });

const css = await emit('app', 'css', minifyCss(await readFile(join(client, 'app.css'), 'utf8')));
const js = await emit('app', 'js', await readFile(join(client, 'app.js'), 'utf8'));
const logo = await emit('logo', 'svg', await readFile(join(client, 'logo.svg'), 'utf8'));
await copyFile(join(client, 'favicon.ico'), join(out, 'favicon.ico'));

const assets = { css, js, logo };
const version = hash(JSON.stringify(assets));
const sw = (await readFile(join(client, 'sw.js'), 'utf8'))
  .replace('__VERSION__', version)
  .replace('__ASSETS__', JSON.stringify(Object.values(assets)));
await writeFile(join(out, 'sw.js'), sw);

await writeFile(
  join(out, '_headers'),
  `/assets/*
  Cache-Control: public, max-age=31536000, immutable
/sw.js
  Cache-Control: no-cache
/favicon.ico
  Cache-Control: public, max-age=604800
`,
);

await mkdir(join(root, 'src', 'generated'), { recursive: true });
await writeFile(
  join(root, 'src', 'generated', 'assets.ts'),
  `// Generated by scripts/build-assets.ts – do not edit.\nexport const ASSETS = ${JSON.stringify(assets, null, 2)} as const;\n`,
);

console.log(`assets built (version ${version}):`, assets);
